name: coe_assembly
description: "[OSANC] Council of Europe Parliamentary Assembly"
schedule: daily
pipeline:
  init:
    method: opensanctions.crawlers.coe_assembly:parse
    params:
      url: 'http://www.assembly.coe.int/nw/xml/AssemblyList/MP-Alpha-EN.asp?initial=%s&offset=0'
    handle:
      pass: store
  store:
    method: opensanctions.helpers:store_entity
