name: eu_whoiswho
description: "[OSANC] EU Who is Who Staff Directory"
schedule: daily
pipeline:
  init:
    method: opensanctions.crawlers.eu_whoiswho:scrape
    handle:
      pass: store
  store:
    method: opensanctions.helpers:store_entity
